export type {
  CommandDispatchEvent,
  CommandDispatchInputLock,
  CommandDispatchOutputAttachedEvent,
  CommandDispatchOutputEndedEvent,
  CommandDispatchOutputGapEvent,
  CommandDispatchOutputGapReason,
  CommandDispatchOutputStream,
  CommandDispatchScope,
  CommandDispatchTarget,
  CommandDispatchTargetStatus,
  CommandDispatchTask,
  CommandDispatchTaskEvent,
  CommandDispatchTaskInput,
  CommandDispatchTaskStatus,
} from './model/types.ts'
