export const mcpScopes = [
  'hosts:read',
  'hosts:probe',
  'sessions:read',
  'sessions:connect',
  'sessions:close',
  'commands:execute',
  'commands:read',
  'commands:interrupt',
  'files:read',
  'files:connect',
  'files:close',
  'files:write',
  'files:delete',
  'files:batch_rename',
  'files:search',
  'files:transfer',
  'files:cancel',
  'system:read',
  'processes:read',
  'processes:terminate',
  'services:read',
  'services:manage',
  'docker:read',
  'docker:manage',
  'crontab:read',
  'crontab:write',
  'forwarding:read',
  'forwarding:manage',
  'snippets:read',
  'snippets:write',
] as const

export type McpScope = (typeof mcpScopes)[number]

export const defaultMcpScopes: McpScope[] = ['hosts:read', 'sessions:read']

export const approvalRequiredScopes: readonly McpScope[] = [
  'commands:execute',
  'files:write',
  'files:delete',
  'files:batch_rename',
  'files:transfer',
  'processes:terminate',
  'services:manage',
  'docker:manage',
  'crontab:write',
  'forwarding:manage',
  'snippets:write',
]
