export type {
  InstallLifecycle,
  UpdateApplicationInfo,
  UpdateCheckInterval,
  UpdateCheckResult,
  UpdateDownloadContext,
  UpdateDownloadProgress,
  UpdateEngine,
  UpdateErrorCode,
  UpdateManagerLogger,
  UpdateManagerOptions,
  UpdatePhase,
  UpdatePreferences,
  UpdatePreferencesPatch,
  UpdateProgress,
  UpdateReleaseInfo,
  UpdateSnapshot,
  UpdateSupport,
} from '#common/contracts'
