export {
  mergeUpdatePreferencesByRevision,
  mergeUpdateRuntimeSnapshot,
  resolveGlobalUpdateStatus,
  selectUpdateNotification,
  updateNotificationStorageKey,
  type GlobalUpdateStatus,
  type GlobalUpdateStatusKind,
  type UpdateNotificationEvent,
  type UpdateNotificationType,
} from './model/updateRuntimeState.ts'
export {
  calculateUpdateEta,
  canPrepareUpdateInstall,
  formatUpdateBytes,
  formatUpdateDuration,
  hasUpdateInstallInterruption,
  isInstallConfirmationCurrent,
  isUpdateWindowPrimaryActionBlocked,
  mergeUpdateWindowBootstrap,
  mergeUpdateWindowSnapshot,
  resolveUpdateWindowPrimaryAction,
  resolveUpdateWindowVisiblePrimaryAction,
  summarizeRuntimeImpact,
  type UpdateWindowBusyAction,
  type UpdateWindowPrimaryAction,
} from './model/updateWindowUiState.ts'
